# -*- coding: utf-8 -*-
"""Data_Science _Assignment_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SJ0BlEVuD6q_A7SRjPjK5Ht6D0nt8Ww

# EDA on International T20 Dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast

df=pd.read_csv("International_T20_Data.csv")

df

df.shape

df.head()

df.tail()

df.info()

df.describe()

df.columns

"""Renaming all the column names to their appropriate names"""

df.rename(columns={
    'innings': 'innings_data',
    'meta.data_version': 'data_version',
    'meta.created': 'created_date',
    'meta.revision': 'revision',
    'info.dates': 'match_date',
    'info.gender': 'gender',
    'info.match_type': 'match_type',
    'info.match_type_number': 'match_number',
    'info.overs': 'overs',
    'info.teams': 'teams',
    'info.outcome.winner': 'winner',
    'info.outcome.by.runs': 'win_by_runs',
    'info.outcome.by.wickets': 'win_by_wickets',
    'info.outcome.method': 'result_method',
    'info.outcome.result': 'result',
    'info.outcome.eliminator': 'eliminator',
    'info.outcome.bowl_out': 'bowl_out_winner',
    'info.player_of_match': 'player_of_match',
    'info.toss.decision': 'toss_decision',
    'info.toss.winner': 'toss_winner',
    'info.venue': 'venue',
    'info.city': 'city',
    'info.umpires': 'umpires',
    'info.neutral_venue': 'neutral_venue',
    'info.supersubs.New Zealand': 'supersub_new_zealand',
    'info.supersubs.South Africa': 'supersub_south_africa',
    'info.bowl_out': 'bowl_out_details'
}, inplace=True)

df

"""Checking the number of null values in each column"""

print(df.isnull().sum())

"""Replacing the null values in 'win_by_wickets' and 'win_by_runs' coloumns by the means value of respective coloumns"""

df['win_by_wickets'] = df['win_by_wickets'].fillna(df['win_by_wickets'].mean())

df['win_by_runs'] = df['win_by_runs'].fillna(df['win_by_runs'].mean())

"""Checking the number of any duplicates in the dataset"""

df.duplicated().sum()

"""Displaying the first 4 columns of the dataset"""

df.iloc[:,:4]

"""Displaying the entries between row 30 and 40 for some specific coloumns"""

df.loc[30:40,['innings_data','match_date','gender','match_type','teams','winner','player_of_match']]

"""Calculating the number of matches played and won by India"""

matches_played = df['teams'].apply(lambda x: 'India' in ast.literal_eval(x)).sum()
matches_won = (df['winner'] == 'India').sum()
print("Matches played by India:", matches_played)
print("Matches won by India:", matches_won)

"""Checking for different types of match formats in dataset"""

df['match_type'].value_counts()

"""Checking the number of matches played by each gender"""

df['gender'].value_counts()

plt.figure()
sns.countplot(x='gender', data=df,palette='Set1')
plt.title("Matches by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Matches")
plt.show()

plt.figure()
sns.boxplot(x='gender', y='win_by_runs', data=df)
plt.title("Win Margin by Gender")
plt.show()

"""Checking the number of matches played and won by each team (sorted according to win percentage)"""

wins = df['winner'].value_counts()
played = {}

for teams in df['teams']:
    team_list = ast.literal_eval(teams)
    for team in team_list:
        played[team] = played.get(team, 0) + 1

played = pd.Series(played)
team_stats = pd.DataFrame({'matches_won': wins,'matches_played': played}).fillna(0)
team_stats['win_percentage'] = (team_stats['matches_won'] / team_stats['matches_played']) * 100
team_stats = team_stats.sort_values(by='win_percentage', ascending=False)
print(team_stats)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,15))
sns.barplot(x=team_stats['win_percentage'], y=team_stats.index, palette='Set1')
plt.title("Team Win Percentage in T20 Matches")
plt.xlabel("Win Percentage")
plt.ylabel("Team")
plt.show()

"""Top 10 teams which played most number of matches"""

played = {}
for teams in df['teams']:
    team_list = ast.literal_eval(teams)
    for team in team_list:
        played[team] = played.get(team, 0) + 1
played = pd.Series(played)
top10 = played.sort_values(ascending=False).head(10)
print(top10)

plt.figure()
sns.barplot(x=top10.values, y=top10.index, palette='pastel')
plt.title("Top 10 Teams by Matches Played")
plt.xlabel("Matches Played")
plt.ylabel("Team")
plt.show()

"""Top 10 teams which won most number of matches

"""

top10_winners = df['winner'].value_counts().head(10)
print(top10_winners)

top_teams = df['winner'].value_counts().head(10)
plt.figure()
sns.barplot(x=top_teams.values, y=top_teams.index, palette='viridis')
plt.title("Top 10 Teams by Match Wins")
plt.xlabel("Number of Wins")
plt.ylabel("Team")
plt.show()

"""Number of tosses won by each team in sorted order"""

df['toss_winner'].value_counts().sort_values(ascending=False)

"""Number of times each player was awarded Player of the match in sorted order"""

df['player_of_match'].value_counts().sort_values(ascending=False)

"""Number of times the team that won the toss also won the match"""

df['toss_match_win'] = (df['toss_winner'] == df['winner'])
df['toss_match_win'].value_counts()

plt.figure()
sns.countplot(x='toss_match_win', data=df, )
plt.title("Did Toss Winner Also Win the Match?")
plt.show()

"""Did toss winner win the match based on decision?"""

pd.crosstab(df['toss_decision'], df['toss_match_win'])

toss_counts = df['toss_decision'].value_counts()
plt.figure()
plt.pie(toss_counts, labels=toss_counts.index, autopct='%1.1f%%')
plt.title("Toss Decision Distribution")
plt.show()

plt.figure()
sns.countplot(x='toss_decision', hue='gender', data=df)
plt.title("Toss Decision by Gender")
plt.show()

"""Top 5 pair of cricket teams who played the most number of T20 matches against each other."""

team_pairs = df['teams'].apply(lambda x: tuple(sorted(ast.literal_eval(x))))
pair_counts = team_pairs.value_counts()
top5 = pair_counts.head(5)
print(top5)

"""Most frequent umpires"""

umpire_list = df['umpires'].dropna().apply(ast.literal_eval)
all_umpires = [umpire for match in umpire_list for umpire in match]
umpire_counts = pd.Series(all_umpires).value_counts()
print(umpire_counts.head())

"""Number of matches played in each year"""

df['year'] = pd.to_datetime(df['created_date']).dt.year
matches_per_year = df.groupby('year').size().sort_index()
print(matches_per_year)

"""in sorted order"""

print(matches_per_year.sort_values(ascending=False))

plt.figure()
matches_per_year.plot(kind='bar',color='green')
plt.title("Matches Played Per Year")
plt.xlabel("Year")
plt.ylabel("Number of Matches")
plt.show()

plt.figure()
sns.lineplot(x=matches_per_year.index, y=matches_per_year.values, color='red')
plt.title("Trend of T20 Matches Over Years")
plt.xlabel("Year")
plt.ylabel("Matches Played")
plt.show()

"""Analysis of matches won by runs"""

df['win_by_runs'].value_counts().sort_values(ascending=False)

print("Biggest win by runs: ")
df['win_by_runs'].max()

print(df['win_by_runs'].mean())

plt.figure()
sns.histplot(df['win_by_runs'], bins=20, color='orange')
plt.title("Distribution of Wins by Runs")
plt.xlabel("Runs Margin")
plt.ylabel("Number of wins")
plt.show()

plt.figure()
sns.boxplot(y=df['win_by_runs'])
plt.title("Spread of Win Margin (Runs)")
plt.ylabel("Win by Runs")
plt.show()

plt.figure()
sns.violinplot(x='gender', y='win_by_runs', data=df, color='green')
plt.title("Win Margin Distribution by Gender")
plt.show()

"""Analysis of matches won by wickets"""

df['win_by_wickets'].value_counts()

print("Biggest win by wickets: ")
df['win_by_wickets'].max()

print("Average wickets by which matches were won")
print(df['win_by_wickets'].mean())

plt.figure()
sns.histplot(df['win_by_wickets'], bins=20, color='yellow')
plt.title("Distribution of Wins by Wickets")
plt.xlabel("Wicket Margin")
plt.ylabel("Number of wins")
plt.show()

plt.figure()
sns.boxplot(y=df['win_by_wickets'])
plt.title("Spread of Win Margin (Wickets)")
plt.ylabel("Win by Runs")
plt.show()

plt.figure()
sns.violinplot(x='gender', y='win_by_wickets', data=df,color='pink')
plt.title("Win Margin Distribution by Gender")
plt.show()

"""Number of matches played at each venue in sorted order"""

df['venue'].value_counts()

"""Top three venues"""

df['venue'].value_counts().head(3)

top_venues = df['venue'].value_counts().head(10)
plt.figure()
top_venues.plot(kind='bar',color=['red','blue','green','orange','purple','pink','yellow','black','skyblue','lightgreen'])
plt.title("Top 10 Venues Hosting T20 Matches")
plt.xlabel("Venue")
plt.ylabel("Matches Played")
plt.xticks(rotation=90)
plt.show()

"""Top five teams by their win percentages"""

temp_df = df.copy()
teams_series = temp_df['teams'].apply(ast.literal_eval)

matches_played = {}

for teams in teams_series:
    for team in teams:
        matches_played[team] = matches_played.get(team, 0) + 1

matches_played = pd.Series(matches_played)
matches_won = temp_df['winner'].value_counts()
team_stats = pd.DataFrame({'matches_played': matches_played, 'matches_won': matches_won}).fillna(0)

team_stats['win_percentage'] = (team_stats['matches_won'] / team_stats['matches_played']) * 100

top5 = team_stats.sort_values(by='win_percentage', ascending=False).head(5)

print(top5)

"""Function to get the scorecard of each match"""

def get_scorecard(innings):

    scorecards = []

    for inn in innings:
        inn_data = list(inn.values())[0]
        team = inn_data['team']
        deliveries = inn_data['deliveries']

        batsman_runs = {}
        bowler_stats = {}

        for ball in deliveries:
            delivery = list(ball.values())[0]
            batsman = delivery['batsman']
            bowler = delivery['bowler']
            runs = delivery['runs']['batsman']
            total_runs = delivery['runs']['total']

            batsman_runs[batsman] = batsman_runs.get(batsman, 0) + runs

            if bowler not in bowler_stats:
                bowler_stats[bowler] = {'runs':0,'wickets':0}
            bowler_stats[bowler]['runs'] += total_runs
            if 'wicket' in delivery:
                bowler_stats[bowler]['wickets'] += 1

        batsman_df = (
            pd.DataFrame(batsman_runs.items(), columns=['Batsman','Runs'])
            .sort_values('Runs', ascending=False)
            .head(4)
            .reset_index(drop=True)
        )
        bowler_df = (
            pd.DataFrame(
                [(k,v['runs'],v['wickets']) for k,v in bowler_stats.items()],
                columns=['Bowler','Runs Conceded','Wickets']
            )
            .sort_values(['Wickets','Runs Conceded'], ascending=[False,True])
            .head(4)
            .reset_index(drop=True)
        )
        scorecard = pd.concat([batsman_df, bowler_df], axis=1)
        scorecards.append((team, scorecard))

    return scorecards

all_scorecards = []

for i in range(len(df)):
    innings_data = ast.literal_eval(df['innings_data'].iloc[i])
    match_scorecards = get_scorecard(innings_data)
    all_scorecards.append(match_scorecards)

"""Printing scorecards of each match"""

all_scorecards

"""Graph for matches played each year"""

plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""# Numpy Operations"""

import numpy as np

arr1 = np.array(np.random.randint(10,55,(6,2)))
print(f"The defined array is \n{arr1}")
print(f" \n The shape of the array is {arr1.shape}")

# Storing the transpose in another matrix object
arr1_tranpose =np.transpose(arr1)
print(f" The transpose of the array is \n{arr1_tranpose}")
print(f" \n The shape of the array is {arr1_tranpose.shape}")

# Now we can reshape this to 1-D,2-D or 3-D array
new_shape = (2,3,2)
reshaped_arr1 = np.reshape(arr1,new_shape)
print(f"The reshaped array is \n{reshaped_arr1}")
print(f" \n The shape of the array is {reshaped_arr1.shape}")

new_shape = (12)
reshaped_arr1 = np.reshape(arr1,new_shape)
print(f"The reshaped array is \n{reshaped_arr1}")
print(f" \n The shape of the array is {reshaped_arr1.shape}")

# 3D Array
new_3d_array = np.array(np.random.randint(13,55,(3,5,4)))
print(f"The defined array is \n{new_3d_array }")
print(f" \n The shape of the array is {new_3d_array .shape}")

# Storing the transpose of the created 3d array
transposed_3d_array =np.transpose(new_3d_array)
print(f" The transpose of the array is \n{transposed_3d_array}")
print(f" \n The shape of the array is {transposed_3d_array.shape}")

# Now we can reshape this to 1-D,2-D or 3-D array
new_shape = (15,4)
reshaped_new_3d_array = np.reshape(new_3d_array,new_shape)
print(f"The reshaped array is \n{reshaped_new_3d_array}")
print(f" \n The shape of the array is {reshaped_new_3d_array.shape}")

new_shape = (60)
reshaped_new_3d_array = np.reshape(new_3d_array,new_shape)
print(f"The reshaped array is \n{reshaped_new_3d_array}")
print(f" \n The shape of the array is {reshaped_new_3d_array.shape}")

# Resize the created 3D array
new_shape = (2,3,6)
resized_new_3d_array = np.resize(new_3d_array,new_shape)
print(f"The resized array is \n{resized_new_3d_array}")
print(f" \n The shape of the array is {resized_new_3d_array.shape}")

#Flattening
new_3d_array.flatten()

#making a 3,3 matrix
mat1 = np.array(np.random.randint(13,55,(3,3)))
mat1

#finding determinant of matrix
det = np.linalg.det(mat1)
print(det)

#finding inverse of matrix
inv = np.linalg.inv(mat1)
print(inv)

#finding eigen values of matrix
print(np.linalg.eig(mat1))

#identity matrix of order 3
np.identity(3)

"""**Manipulating Numpy arrays**"""

a = np.random.randint(17,60,(3,4,5))
print(a)
print(a.shape)

#Insert along axis =0
np.insert(a,1,50,axis=0)

# Insert along axis = 1
np.insert(a,0,50,axis=1)

# Insert along axis=2
np.insert(a,0,50,axis=2)

# Append a value to the array. It flattens the array and append 50 to the end
np.append(a, 50)

a

# Delete along Axis=0
np.delete(a,(0),axis = 0)

# Delete along axis=1
np.delete(a,(0,2),axis = 1)

np.delete(a,(0,1),axis = 2)

#unique values in a
np.unique(a)

# Find all the unique values within the array a.
#The return_counts=True argument makes the function also return
#how many times each unique value appears in the array.
#The output is a tuple, with the first part being the unique values and the second part being their respective counts.
np.unique(a,return_counts=True)

#also returns the indes of the unique elements in the third tuple
np.unique(a,return_counts=True, return_index=True)

np.arange(3)

np.arange(3) + 5

np.ones((3,3))

np.ones((3,3)) + np.arange(3)

np.arange(3).reshape((3,1))

np.arange(3).reshape((3,1)) + np.arange(3)

np.arange(3).reshape((3,1)) + np.arange(5)

a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,10,(2,4))
print(b)

#adding two 2D arrays
np.add(a,b)

#subtracting two arrays
np.subtract(a,b)

#multiplying two arrays
np.multiply(a,b)

#dividing two arrays
np.divide(a,b)

a=np.random.randint(15,99,(3,4))
print(a)

#sum of all elements of array
print(np.sum(a))

#sum of all elements of array along axis 0 i.e y axis
np.sum(a,axis=0)

#sum of all elements of array along axis 1 i.e x axis
np.sum(a,axis=1)

#maximum element of array
print(np.max(a))

#maximum element of array
print(np.min(a))

#maximum element of array in each coloumn i.e axis 0
print("maximum element of array in each coloumn")
np.max(a,axis=0)

#maximum element of array in each row i.e axis 1
print("maximum element of array in each row")
np.min(a,axis=1)

#minimum element of array in each coloumn i.e axis 0
print("minimum element of array in each coloumn")
np.min(a,axis=0)

#minimum element of array in each crow i.e axis 1
print("minimum element of array in each coloumn")
np.min(a,axis=1)

#sorting array along coloumn
np.sort(a,axis=0)

#sorting array along row
np.sort(a,axis=1)

